apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: monitor-operator
  template:
    metadata:
      labels:
        name: monitor-operator
    spec:
      serviceAccountName: monitor-operator
      containers:
        - name: monitor-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - monitor-operator
          imagePullPolicy: Always
          volumeMounts:
          - name: config-volume
            mountPath: /etc/monitor-operator
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "monitor-operator"
            - name: AWX_URL
              valueFrom:
                secretKeyRef:
                  name: monitor-operator-secret
                  key: url
            - name: AWX_USER
              valueFrom:
                secretKeyRef:
                  name: monitor-operator-secret
                  key: username
            - name: AWX_PW
              valueFrom:
                secretKeyRef:
                  name: monitor-operator-secret
                  key: password
      volumes:
        - name: config-volume
          configMap:
            name: monitor-operator-conf
            items:
            - key: monitor-operator-conf
              path: monitor-operator-conf.yml