apiVersion: v1
kind: Service
metadata:
  name: telegraf
  namespace: openshift-monitoring
  labels:
    k8s-app: telegraf-daemonset
spec:
  ports:
    - name: https
      port: 9100
      protocol: TCP
      targetPort: https
  selector:
    name: telegraf-daemonset
  type: ClusterIP